#!/bin/bash
MKLINCLUDE="-I${MKLROOT}/include"
MKLLINK="${MKLROOT}/lib/libmkl_intel_lp64.a ${MKLROOT}/lib/libmkl_core.a ${MKLROOT}/lib/libmkl_sequential.a -lpthread -lm"
FC=ifort
FFLAGS=" -O2 -fixed"

$FC $FFLAGS -c stellgap_worker.f
$FC $FFLAGS -c Fourier_lib_convolve.f
$FC $FFLAGS -c fitpack.f
$FC $FFLAGS -o xstgap_worker -I. $MKLINCLUDE $MKLLINK stellgap_worker.o Fourier_lib_convolve.o fitpack.o
